AcademyReview.MVC/Controllers/AcademyController.cs
using AcademyReview.Models.AcademyModels;
using AcademyReview.Models.RatingModels.Academy;
using AcademyReview.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AcademyReview.MVC.Controllers
{
    public class AcademyController : Controller
    {
        // GET: Academy
        public async Task<ActionResult> Index()
        {
            var service = GetAcademyService();
            return View(await service.GetAllAcademiesAsync());
        }
        [HttpGet, Authorize(Roles = "Admin, User")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost, Authorize(Roles = "Admin, User")]
        public ActionResult Create(AcademyCreate model)
        {
            if (ModelState.IsValid)
            {
                var service = GetAcademyService();
                if (service.CreateAcademy(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        [HttpGet, Authorize(Roles = "Admin, User")]
        public ActionResult Rate(int id)
        {
            var service = GetAcademyService();
            ViewBag.Detail = service.GetAcademyById(id);

            var model = new AcademyRatingCreate { AcademyId = id };
            return View(model);
        }

        //HttpPost
        [HttpPost, Authorize(Roles = "Admin, User")]
        public ActionResult Rate(AcademyRatingCreate model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.CreateAcademyRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        [HttpGet, AllowAnonymous]
        public ActionResult Ratings(int id)
        {
            var service = new RatingService(User.Identity.GetUserId());
            @ViewBag.id = id;
            var model = service.GetAnAcademyRatings(id);
            //var modelList = new List<AcademyRatingListItem>();

            //ViewBag.Name = model.

            return View(model);
        }
        [HttpGet]
        public ActionResult DeleteRating(int id)
        {
            var model = new AcademyRatingDelete { Id = id };

            return View(model);
        }
        [HttpPost]
        public ActionResult DeleteRating(AcademyRatingDelete model)
        {
            if(ModelState.IsValid)
            {
                var service = new BrowsingService(User.Identity.GetUserId());
                if (service.DeleteRating(model.Id))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult EditRating(int id)
        {
            var model = new RatingEdit { Id = id };
            return View(model);
        }
        [HttpPost]
        public ActionResult EditRating(RatingEdit model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.UpdateRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        //HttpGet 
        [HttpGet, Authorize (Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = GetAcademyService();

            var detail = service.GetAcademyById(id);
            var model = new AcademyEdit
            {
                AcademyId = id,
                Name = detail.Name,
                City = detail.City,
                State = detail.State
            };
            return View(model);
        }

        //HttpPost
        [HttpPost, Authorize (Roles = "Admin")]
        public ActionResult Edit(AcademyEdit model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            var service = GetAcademyService();
            if (service.UpdateAcademyByIdAsync(model))
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Academy couldn't be updated.");
                return View(model);
        }
        //HttpGet Details
        [HttpGet, AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = GetAcademyService();
            var model = service.GetAcademyByDetail(id);
            return View(model);
        }
        //HttpGet
        [HttpGet, Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = GetAcademyService();

            var model = service.GetAcademyByDetail(id);

            return View(model);
        }
        [HttpPost, ActionName("Delete"), Authorize (Roles = "Admin")]
        public ActionResult DeleteAcademy(int id)
        {
            var service = GetAcademyService();
            if (service.DeleteAcademyById(id))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete", new { id });
        }
        private AcademyService GetAcademyService()
        {
            var userId = User.Identity.GetUserId();
            var service = new AcademyService(userId);
            return service;
        }
    }
}

AcademyReview.MVC/Controllers/ProgramController.cs
using AcademyReview.Data;
using AcademyReview.Models.AcademyModels;
using AcademyReview.Models.ProgramModels;
using AcademyReview.Models.RatingModels.Academy;
using AcademyReview.Models.RatingModels.Program;
using AcademyReview.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AcademyReview.MVC.Controllers
{
    public class ProgramController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var service = GetProgramService();
            return View(await service.GetAllProgramsAsync());
        }
        [HttpGet, Authorize(Roles = "Admin, User")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost, Authorize(Roles = "Admin, User")]
        public ActionResult Create(ProgramCreate model)
        {
            var ctx = new ApplicationDbContext();
            if (ctx.Academies.FirstOrDefault(a=>a.Name == model.AcademyName)==null)
            {
                ModelState.AddModelError("AcademyName", "Please create the academy first or enter an academy that already exists");
                return View(model);
            }
            var service = GetProgramService();
            if (service.CreateProgram(model))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        //HttpGet Rate(int id)
        [HttpGet, Authorize(Roles = "Admin, User")]
        public ActionResult Rate(int id)
        {
            var service = GetProgramService();
            ViewBag.Detail = service.GetProgramById(id);

            var model = new ProgramRatingCreate { ProgramId = id };
            return View(model);
        }
        //HttpPost Rate(ProgramRatingCreate model)
        [HttpPost, Authorize(Roles = "Admin, User")]
        public ActionResult Rate(ProgramRatingCreate model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.CreateProgramRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        [HttpGet, AllowAnonymous]
        public ActionResult Ratings(int id)
        {
            var service = new RatingService(User.Identity.GetUserId());
            var model = service.GetAnProgramRatings(id);

            return View(model);
        }
        [HttpGet]
        public ActionResult EditRating(int id)
        {
            var model = new RatingEdit { Id = id };
            return View(model);
        }
        [HttpPost]
        public ActionResult EditRating(RatingEdit model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.UpdateRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        //HttpGet Edit
        [HttpGet, Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = GetProgramService();

            var detail = service.GetProgramById(id);
            var model = new ProgramEdit
            {
                ProgramId = detail.ProgramId,
                Name = detail.Name,
                Type = detail.Type,
                Prerequisite = detail.Prerequisite,
                AcademyId = detail.AcademyId,
                AcademyName = detail.AcademyName
            };
            return View(model);
        }
        //HttpPost Edit
        [HttpPost, Authorize(Roles = "Admin")]
        public ActionResult Edit(ProgramEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = GetProgramService();
            if (service.UpdateProgramByIdAsync(model))
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Academy couldn't be updated.");
            return View(model);
        }
        [HttpGet, AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = GetProgramService();
            var model = service.GetProgramByDetail(id);

            return View(model);
        }
        //HttpGet Delete
        [HttpGet, Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = GetProgramService();

            var model = service.GetProgramById(id);

            return View(model);
        }
        //HttpPost Delete
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteProgram(int id)
        {
            var service = GetProgramService();
            if (service.DeleteProgramById(id))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete", new { id });
        }
        private ProgramService GetProgramService()
        {

            var userId = User.Identity.GetUserId();
            var service = new ProgramService(userId);
            return service;
        }
    }
}

AcademyReview.MVC/Views/Program/Create.cshtml
@model AcademyReview.Models.ProgramModels.ProgramCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProgramCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prerequisite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prerequisite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prerequisite, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.AcademyId)
        @*<div class="form-group">
                @Html.LabelFor(model => model.AcademyId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AcademyId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AcademyId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.AcademyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AcademyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.AcademyName)
                @*@Html.ValidationMessageFor(model => model.AcademyName, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    | @Html.ActionLink("Back", "Index") |
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AcademyReview.MVC/Views/Program/Delete.cshtml
@model AcademyReview.Models.ProgramModels.ProgramDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Program?</h3>
<div>
    <h4>ProgramDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
                @Html.DisplayNameFor(model => model.ProgramId)
            </dt>*@

        <dd>
            @*@Html.DisplayFor(model => model.ProgramId)*@
            @Html.HiddenFor(model => model.ProgramId)

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prerequisite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prerequisite)
        </dd>
        @Html.HiddenFor(model => model.AcademyId)

        @*<dt>
                @Html.DisplayNameFor(model => model.AcademyId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AcademyId)
            </dd>*@

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
        </div>
    }
</div>
    | @Html.ActionLink("Back", "Index") |

AcademyReview.MVC/Views/Program/Details.cshtml
@model AcademyReview.Models.ProgramModels.ProgramDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ProgramDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.ProgramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramId)
        </dd>*@
        @Html.HiddenFor(model => model.ProgramId)

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prerequisite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prerequisite)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.AcademyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AcademyId)
        </dd>*@
        @Html.HiddenFor(model => model.AcademyId)

        <dt>
            @Html.DisplayNameFor(model => model.AcademyName)
        </dt>
        @Html.HiddenFor(model => model.Ratings)
        <dd>
            @Html.DisplayFor(model => model.AcademyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AverageRating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AverageRating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

    </dl>
</div>
<p>
    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ProgramId }) 
}
    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
    {
        @Html.ActionLink("Delete", "Delete", new { id = Model.ProgramId }) 
    }
    @Html.ActionLink("Back", "Index")
</p>

AcademyReview.MVC/Views/Program/Edit.cshtml
@model AcademyReview.Models.ProgramModels.ProgramEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ProgramEdit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProgramId)

    @*<div class="form-group">
            @Html.LabelFor(model => model.ProgramId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prerequisite, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Prerequisite, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Prerequisite, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.AcademyId)
    @*<div class="form-group">
            @Html.LabelFor(model => model.AcademyId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AcademyId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AcademyId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
   | @Html.ActionLink("Back", "Index") |
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AcademyReview.MVC/Views/Program/EditRating.cshtml
@model AcademyReview.Models.RatingModels.Academy.RatingEdit

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RatingEdit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
   | @Html.ActionLink("Back to List", "Index") |
</div>

AcademyReview.MVC/Views/Program/Index.cshtml
@model IEnumerable<AcademyReview.Models.ProgramModels.ProgramListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Program Rankings</h2>

<p>
    @Html.ActionLink("Add Program", "Create", "Program")
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.ProgramId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.AcademyId)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.AcademyName)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prerequisite)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.AverageRating)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
                @Html.HiddenFor(modelItem => item.ProgramId)
            @*<td>
                @Html.DisplayFor(modelItem => item.ProgramId)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @Html.HiddenFor(modelItem => item.AcademyId)
            <td>
                @Html.DisplayFor(modelItem => item.AcademyName)
            </td>
            @Html.HiddenFor(modelItem => item.Type)
            @Html.HiddenFor(modelItem => item.Prerequisite)
            <td>
                @Html.DisplayFor(modelItem => item.AverageRating)
            </td>
            <td>
                | @Html.ActionLink("Rate", "Rate", new { id = item.ProgramId }) |
                | @Html.ActionLink("Details", "Details", new { id = item.ProgramId }) |
                | @Html.ActionLink("View Ratings", "Ratings", new { id = item.ProgramId }) |
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ProgramId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ProgramId })
                </td>*@
        </tr>
    }

</table>

AcademyReview.MVC/Views/Program/Rate.cshtml
@model AcademyReview.Models.RatingModels.Program.ProgramRatingCreate

@{
    ViewBag.Title = "Rate";
}

<h2>Rate</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ProgramRatingCreate</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ProgramId)


    <div class="form-group">
        @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.ProgramId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
   | @Html.ActionLink("Back", "Index") |
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AcademyReview.MVC/Views/Program/Ratings.cshtml
@model IEnumerable<AcademyReview.Models.RatingModels.Program.ProgramRatingListItem>

@{
    ViewBag.Title = "Ratings";
}

<h2>Program Ratings</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.RatingId)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.IsUserOwned)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.ProgramId)
            </th>*@
        @*<th>
                @Html.DisplayNameFor(model => model.ProgramName)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.RatingId)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.IsUserOwned)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProgramId)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.ProgramName)
                </td>*@
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
            <td>| @Html.ActionLink("Edit", "EditRating", "Academy", new { id = item.RatingId }, null) |</td>

        </tr>
    }

</table>
| @Html.ActionLink("Back", "Index") |