AcademyReview.MVC/Controllers/InstructorController.cs
using AcademyReview.Models.InstructorModels;
using AcademyReview.Models.RatingModels.Academy;
using AcademyReview.Models.RatingModels.Instructor;
using AcademyReview.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AcademyReview.MVC.Controllers
{
    public class InstructorController : Controller
    {
        // GET: Instructor
        public ActionResult Index()
        {
            var service = GetInstructorService();
            return View(service.GetAllInstructors());
        }
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Create(InstructorCreate model)
        {
            if (ModelState.IsValid)
            {
                var service = GetInstructorService();
                if (service.CreateInstructor(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        //HttpGet Rate(int id)
        [HttpGet]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Rate(int id)
        {
            var service = GetInstructorService();
            ViewBag.Detail = service.GetInstructorById(id);
            var entity = service.GetInstructorById(id);
            var model = new InstructorRatingCreate { InstructorId = entity.InstructorId };
            return View(model);
        }
        //HttpPost Rate(ProgramRatingCreate model)
        [HttpPost]
        [Authorize(Roles = "Admin, User")]
        public ActionResult Rate(InstructorRatingCreate model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.CreateInstructorRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        [HttpGet, AllowAnonymous]
        public ActionResult Ratings(int id)
        {
            var service = new RatingService(User.Identity.GetUserId());
            var model = service.GetAnInstructorRatings(id);

            return View(model);
        }
        [HttpGet]
        public ActionResult EditRating(int id)
        {
            var model = new RatingEdit { Id = id };
            return View(model);
        }
        [HttpPost]
        public ActionResult EditRating(RatingEdit model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.UpdateRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        //HttpGet Edit
        [HttpGet, Authorize (Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = GetInstructorService();
            var model = service.GetInstructorById(id);
            //int academyId = model.AcademyId;
            //int programId = model.ProgramId;
            //string academyName = service.GetAcademyNameById(academyId);
            //string programName = service.GetProgramNameById(programId);
            var newModel = new InstructorEdit();
            {
                newModel.InstructorId = model.InstructorId;
                newModel.FullName = model.FullName;
                newModel.ProgramId = model.ProgramId;
                newModel.ProgramName = model.ProgramName;
                newModel.AcademyId = model.AcademyId;
                newModel.AcademyName = model.AcademyName;
            };
            return View(model);
        }
        //HttpPost Edit
        [HttpPost, Authorize (Roles = "Admin")]
        public ActionResult Edit(InstructorEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = GetInstructorService();
            if (service.UpdateInstructor(model))
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Academy couldn't be updated.");
            return View(model);
        }
        //HttpGet Details
        [HttpGet, AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = GetInstructorService();
            var model = service.GetInstructorByDetail(id);

            return View(model);
        }
        //HttpGet Delete
        [HttpGet, Authorize (Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = GetInstructorService();

            var model = service.GetInstructorById(id);

            return View(model);
        }
        //HttpPost Delete
        [HttpPost, ActionName("Delete"), Authorize (Roles = "Admin")]
        public ActionResult DeleteProgram(int id)
        {
            var service = GetInstructorService();
            if (service.DeleteInstructorById(id))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete", new { id });
        }
        private InstructorService GetInstructorService()
        {

            var userId = User.Identity.GetUserId();
            var service = new InstructorService(userId);
            return service;
        }
    }
}

AcademyReview.MVC/Controllers/ProgramController.cs
using AcademyReview.Data;
using AcademyReview.Models.AcademyModels;
using AcademyReview.Models.ProgramModels;
using AcademyReview.Models.RatingModels.Academy;
using AcademyReview.Models.RatingModels.Program;
using AcademyReview.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AcademyReview.MVC.Controllers
{
    public class ProgramController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var service = GetProgramService();
            return View(await service.GetAllProgramsAsync());
        }
        [HttpGet, Authorize(Roles = "Admin, User")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost, Authorize(Roles = "Admin, User")]
        public ActionResult Create(ProgramCreate model)
        {
            var ctx = new ApplicationDbContext();
            if (ctx.Academies.FirstOrDefault(a=>a.Name == model.AcademyName)==null)
            {
                ModelState.AddModelError("AcademyName", "Please create the academy first or enter an academy that already exists");
                return View(model);
            }
            var service = GetProgramService();
            if (service.CreateProgram(model))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        //HttpGet Rate(int id)
        [HttpGet, Authorize(Roles = "Admin, User")]
        public ActionResult Rate(int id)
        {
            var service = GetProgramService();
            ViewBag.Detail = service.GetProgramById(id);

            var model = new ProgramRatingCreate { ProgramId = id };
            return View(model);
        }
        //HttpPost Rate(ProgramRatingCreate model)
        [HttpPost, Authorize(Roles = "Admin, User")]
        public ActionResult Rate(ProgramRatingCreate model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.CreateProgramRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        [HttpGet, AllowAnonymous]
        public ActionResult Ratings(int id)
        {
            var service = new RatingService(User.Identity.GetUserId());
            var model = service.GetAnProgramRatings(id);

            return View(model);
        }
        [HttpGet]
        public ActionResult EditRating(int id)
        {
            var model = new RatingEdit { Id = id };
            return View(model);
        }
        [HttpPost]
        public ActionResult EditRating(RatingEdit model)
        {
            if (ModelState.IsValid)
            {
                var service = new RatingService(User.Identity.GetUserId());
                if (service.UpdateRating(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        //HttpGet Edit
        [HttpGet, Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var service = GetProgramService();

            var detail = service.GetProgramById(id);
            var model = new ProgramEdit
            {
                ProgramId = detail.ProgramId,
                Name = detail.Name,
                Type = detail.Type,
                Prerequisite = detail.Prerequisite,
                AcademyId = detail.AcademyId,
                AcademyName = detail.AcademyName
            };
            return View(model);
        }
        //HttpPost Edit
        [HttpPost, Authorize(Roles = "Admin")]
        public ActionResult Edit(ProgramEdit model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = GetProgramService();
            if (service.UpdateProgramByIdAsync(model))
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Academy couldn't be updated.");
            return View(model);
        }
        [HttpGet, AllowAnonymous]
        public ActionResult Details(int id)
        {
            var service = GetProgramService();
            var model = service.GetProgramByDetail(id);

            return View(model);
        }
        //HttpGet Delete
        [HttpGet, Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var service = GetProgramService();

            var model = service.GetProgramById(id);

            return View(model);
        }
        //HttpPost Delete
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteProgram(int id)
        {
            var service = GetProgramService();
            if (service.DeleteProgramById(id))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete", new { id });
        }
        private ProgramService GetProgramService()
        {

            var userId = User.Identity.GetUserId();
            var service = new ProgramService(userId);
            return service;
        }
    }
}

AcademyReview.MVC/Controllers/SearchController.cs
using AcademyReview.Data;
using AcademyReview.Models.AcademyModels;
using AcademyReview.Models.InstructorModels;
using AcademyReview.Models.ProgramModels;
using AcademyReview.Models.RatingModels.Academy;
using AcademyReview.Models.SearchModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AcademyReview.MVC.Controllers
{
    public class SearchController : Controller
    {
        // GET: Rating
        //public ActionResult Index()
        //{

        //    return View();
        //}
        public ActionResult Index(string id)
        {
            return View();
        }
        //public ActionResult Search()
        //{
        //    return View();
        //}
        //public ActionResult Search(SearchParameters model)
        //{
        //    if(model.TypeId == SearchBy.Academy)
        //    {
        //        var ctx = new ApplicationDbContext();
        //        var model = 
        //    }
        //}
        //public ActionResult Academies()
        //{
        //    return View();
        //}
        public ActionResult Academies(string id)
        {
            var ctx = new ApplicationDbContext();
            var academies = from a in ctx.Academies
                            select a;

            if (!String.IsNullOrEmpty(id))
            {
                academies = academies.Where(a => a.Name.Contains(id));
                //double averageRating = ctx.Academies.FirstOrDefault(a => a.Name.Contains(id)).AverageRating;
                var list = academies.Select(a => new AcademySearchItem
                {
                    Id = a.AcademyId,
                    Name = a.Name,
                    City = a.City,
                    State = a.State
                }).ToList();
            return View(list);
            }
            var emptyList = new List<AcademySearchItem>();
            return View(emptyList);
        }
        //public PartialViewResult Academies2()
        //{
        //    return PartialView();
        //}
        //public PartialViewResult Academies2(string id)
        //{
        //    var ctx = new ApplicationDbContext();
        //    var academies = from a in ctx.Academies
        //                    select a;

        //    if (!String.IsNullOrEmpty(id))
        //    {
        //        academies = academies.Where(a => a.Name.Contains(id));
        //        //double averageRating = ctx.Academies.FirstOrDefault(a => a.Name.Contains(id)).AverageRating;
        //        var list = academies.Select(a => new AcademySearchItem
        //        {
        //            Id = a.AcademyId,
        //            Name = a.Name,
        //            City = a.City,
        //            State = a.State
        //        }).ToList();
        //        return PartialView(list);
        //    }
        //    var emptyList = new List<AcademySearchItem>();
        //    return PartialView(emptyList);
        //}
        public ActionResult Programs(string id)
        {
            var ctx = new ApplicationDbContext();
            var programs = from p in ctx.Programs
                            select p;

            if (!String.IsNullOrEmpty(id))
            {
                programs = programs.Where(a => a.Name.Contains(id));
                //double averageRating = ctx.Academies.FirstOrDefault(a => a.Name.Contains(id)).AverageRating;
                var list = programs.Select(a => new ProgramSearchItem
                {
                    Id = a.ProgramId,
                    Name = a.Name,
                    Type = a.Type,
                    AcademyName = a.AcademyName
                }).ToList();
                return View(list);
            }
            var emptyList = new List<ProgramSearchItem>();
            return View(emptyList);
        }
        public ActionResult Instructors(string id)
        {
            var ctx = new ApplicationDbContext();
            var instructors = from i in ctx.Instructors
                           select i;

            if (!String.IsNullOrEmpty(id))
            {
                instructors = instructors.Where(a => a.FullName.Contains(id));
                //double averageRating = ctx.Academies.FirstOrDefault(a => a.Name.Contains(id)).AverageRating;
                var list = instructors.Select(a => new InstructorSearchItem
                {
                    Id = a.InstructorId,
                    FullName = a.FullName,
                    AcademyName = a.AcademyName,
                    ProgramName = a.ProgramName
                }).ToList();
                return View(list);
            }
            var emptyList = new List<InstructorSearchItem>();
            return View(emptyList);
        }
    }
}

AcademyReview.MVC/Views/Search/Academies.cshtml
@model IEnumerable<AcademyReview.Models.AcademyModels.AcademySearchItem>

@{
    ViewBag.Title = "SearchAcademies";
}

<h2>SearchAcademies</h2>

<form asp-controller="Rating" asp-action="Academies">
    <p>
        Title: <input type="text" name="Id">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model=>model.Id)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageRating)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
            @Html.HiddenFor(modelItem => item.Id)
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AverageRating)
        </td>
        <td>
           | @Html.ActionLink("Details", "Details", "Academy", new { id = item.Id }, null) |
          
        </td>
    </tr>
}

</table>

AcademyReview.MVC/Views/Search/Academies2.cshtml
@model IEnumerable<AcademyReview.Models.AcademyModels.AcademySearchItem>


<form asp-controller="Rating" asp-action="Academies2">
    <p>
        Title: <input type="text" name="Id">
        <input type="submit" value="Filter" />
    </p>
</form>
    @if(Model==null){
        <div></div>
    }
    else
    {

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageRating)
        </th>
        <th></th>
    </tr>

        @foreach (var item in Model)
        {
            <tr>
                @Html.HiddenFor(modelItem => item.Id)

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AverageRating)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    | @Html.ActionLink("Details", "Details", "Academy", new { id = item.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

</table>
    }

AcademyReview.MVC/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Search</h1>
<h2 id="searchHeaders">| @Html.ActionLink("Academies", "Academies", "Search") |</h2>
<h2 id="searchHeaders">| @Html.ActionLink("Programs", "Programs", "Search") |</h2>
<h2 id="searchHeaders">| @Html.ActionLink("Instructors", "Instructors", "Search") |</h2>























@*<button id="search">Search</button>

<script>
var url = '@Url.Action("DisplaySearchResults", "Search")';
$('#search').click(function() {
  var keyWord = $('#Keyword').val();
  $('#searchResults').load(url, { searchText: keyWord });
})
</script>


<form asp-controller="Rating" asp-action="Academies2">
    <p>
        Title: <input type="text" name="Id">
        <input type="submit" value="Filter" />
    </p>
</form>

<div>

    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#first" aria-controls="first" role="tab" data-toggle="tab">First</a></li>
        <li role="presentation"><a href="#second" aria-controls="second" role="tab" data-toggle="tab">Second</a></li>
    </ul>

    <div class="panel-body tab-content">
        <div class="tab-pane active" id="first">
            @Html.Partial("Academies2", )
        </div>
        <div class="tab-pane" id="second">
            @Html.ActionLink("Programs", "Search")
        </div>
    </div>

</div>*@

AcademyReview.MVC/Views/Search/Instructors.cshtml
@model IEnumerable<AcademyReview.Models.InstructorModels.InstructorSearchItem>

@{
    ViewBag.Title = "Instructors";
}

<h2>Instructors</h2>

<form asp-controller="Rating" asp-action="Instructors">
    <p>
        Search: <input type="text" name="Id">
        <input type="submit" value="Filter" />
    </p>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AcademyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProgramName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @Html.HiddenFor(modelItem => item.Id)
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AcademyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProgramName)
        </td>
        <td>
           | @Html.ActionLink("Edit", "Edit", "Instructor", new { id=item.Id }, null) |
           | @Html.ActionLink("Details", "Details", "Instructor", new { id = item.Id }, null) |
           | @Html.ActionLink("Delete", "Delete", "Instructor", new { id=item.Id }, null) |
        </td>
    </tr>
}

</table>

AcademyReview.MVC/Views/Search/Programs.cshtml
@model IEnumerable<AcademyReview.Models.ProgramModels.ProgramSearchItem>

@{
    ViewBag.Title = "Programs";
}

<h2>Programs</h2>

<form asp-controller="Rating" asp-action="Programs">
    <p>
        Search: <input type="text" name="Id">
        <input type="submit" value="Filter" />
    </p>
</form>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AcademyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @Html.HiddenFor(modelItem => item.Id)
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AcademyName)
        </td>
        <td>
            | @Html.ActionLink("Rate", "Rate", "Program", new { id = item.Id}, null) |
            | @Html.ActionLink("Details", "Details", "Program", new { id = item.Id }, null) |
            | @Html.ActionLink("View Ratings", "Ratings", "Program", new { id = item.Id }, null) |
        </td>
    </tr>
}

</table>

AcademyReview.MVC/Views/Search/Search.cshtml
@model AcademyReview.Models.SearchModels.SearchParameters

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SearchParameters</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TypeId)
        <div class="col-md-10">
            @Html.DropDownList("SearchParameters",
                                new SelectList(Enum.GetValues(typeof(Type))),
                                "Search By:",
                                new { @class = "form-control" })

        </div>
        @Html.LabelFor(model => model.SearchInput, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SearchInput, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SearchInput, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    | @Html.ActionLink("Back to List", "Index") |
</div>